### ISSUE TITLE
Help with parameters

### ISSUE THREAD

**Issue by robdejonge** [MiGoller/docker-http-mqtt-bridge#1]
My MQTT server does not require a username and password. Will it work to just omit the `MQTT_USER` and `MQTT_PASS` parameters?

Also, the `AUTH_KEY` .. where is this used? Can I just put any random string of letters and numbers in there? What is it for?

**Comment by MiGoller** [comment]
Hey @robdejonge ,

sorry for responding so late. 

Yes, feel free to omit `MQTT_USER` and `MQTT_PASS`, if your broker doesn't require any authentication and allows anonymous connections. HiveMQ provides a free public broker for testing purposes without authentication: `mqtt://broker.hivemq.com:1883`.

The `AUTH_KEY` is like an `API secret`. If you set `AUTH_KEY` any request must submit the matching phrase as part of the JSON. The bridge will publish the message to the topic only if the request's secrets matches `AUTH_KEY`. If you omit `AUTH_KEY` anybody could publish messages to your broker! Most web-hooks like IFTTT Marker-webhooks do not support authentication methods like basic auth, so this will be your only option the harden your bridge.

For further questions I'm happy to help you.

KR,
Michael

**Comment by robdejonge** [comment]
Thank you for taking the time to write this explanation! Much appreciated.
