### ISSUE TITLE
Error when sending...

### ISSUE THREAD

**Issue by helianto** [MiGoller/docker-http-mqtt-bridge#2]
when i try to send a message i received: 
"Unauthorized"

In the log of docker:   
Received request [/post] from [::ffff:192.168.1.2].

quest is not authorized.

**Comment by MiGoller** [comment]
Hey @helianto ,

thank you for your feedback.

I guess you receive the `Unauthorized` in the browser when trying to post a request to the bridge, right? If you have a look at the console log you should notice a error message `Request is not authorized.` .

In that case you've set an `AUTH_KEY` for the bridge, but you do not provide this secret in the JSON object of your POST-request.

Am I right?

KR,
Michael

**Comment by MYeager1967** [comment]
I probably have a similar issue so I just tacked it on here. I have got the container running, and I have tried several times to remove the AUTH_KEY environment variable to see if it makes a difference, but the "http://192.168.0.3:82/post?topic=/MyTopic/TestTopic&path=on" command gets me a response that it "Cannot GET /post?topic=/MyTopic/TestTopic&path=on". I'm certain that it's something stupid, but I'm killing myself trying to figure it out. If I need the AUTH_KEY in the http command, I just need to know how to do it...

**Comment by jaakla** [comment]
> but you do not provide this secret in the JSON object of your POST-request.

Can you point to line in the readme where this is documented when and how exactly to do that?

**Comment by jaakla** [comment]
I answer myself,  following works:
```
{"topic" : "MyTopic", "message" : "Hello World", "key": "912ec803b2ce49e4a541068d495ab570"}
```

**Comment by MiGoller** [comment]
Hey @jaakla . Sorry for responding so lately. You're right. You have to provide the `key` within the JSON-payload.

Please have a look at https://github.com/petkov/http_to_mqtt#usage for further details. The `key` is explained on how to setup Maker Webhooks.

KR, MiGoller
